name: Deploy Cloud Function

on:
  push:
    branches:
      - prod
      - stage
    paths:
      - "sources/**"

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/prod' || github.ref == 'refs/heads/stage'
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v0.3.0
        with:
          version: 'latest'
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          
      - name: Configure gcloud CLI
        run: gcloud config set project ${{ secrets.GCP_PROJECT_ID }}

      - name: Deploy Cloud Function
        run: |
          gcloud functions deploy "ph_clfunction" \
            --entry-point main \
            --runtime python38 \
            --trigger-http \
            --region ${{ secrets.REGION }} \
            --source "webapp_upload/function.zip" \
            --update-env-vars MYSQL_CONNECTION_STRING=${{ secrets.MYSQL_CONNECTION_STRING }}
  
  test:
    runs-on: ubuntu-latest
    needs: deploy
    if: github.ref == 'refs/heads/prod' || github.ref == 'refs/heads/stage'
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          cd sources
          pip install -r requirements.txt

      - name: Run tests
        run: |
          cd sources
          pytest

      - name: Test Cloud Function
        run: |
          gcloud functions call "ph_clfunction" \
            --region ${{ secrets.REGION }} \
            --data '{ "key": "value" }'